name: gis-toolkit
services:
  app:
    build: .
    ports:
      - "8010:5010"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - default
    working_dir: /app
    command: python app.py

networks:
  default:
    driver: bridge
